
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./web:/app
      - web_node_modules:/app/node_modules
    depends_on:
      - mongodb
    environment:
      DB_HOST:     mongodb
      DB_PORT:     27017
      DB_NAME:     TEST
      DB_USER:     root
      DB_PASSWORD: 1234
    command: >
      sh -c "
        echo 'Waiting for MongoDB to be ready...'
        while ! nc -z mongodb 27017; do
          sleep 1
        done
        echo 'MongoDB is ready!'
        node server.js
      "

  mongodb:
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: TEST
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./db/data:/data/db
    ports:
      - "27017:27017"

volumes:
  web_node_modules:

