
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./web:/app
      - web_node_modules:/app/node_modules
    depends_on:
      - mongodb
    environment:
      DB_HOST:     mongodb
      DB_PORT:     27017
      DB_NAME:     TEST
      DB_USER:     root
      DB_PASSWORD: 1234
      JWT_SECRET:  'a_very_secret_and_secure_key_that_should_be_generated'
   
  mongodb:
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: TEST
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./db/data:/data/db
    ports:
      - "27017:27017"

volumes:
  web_node_modules:

